issues:
  exclude-use-default: true
  exclude:
    # Triggered by long table tests.
    - Function 'Test\w+' is too long

linters:
  enable-all: true
  disable:
    # Linters that are deprecated.
    - exhaustivestruct
    - scopelint
    - interfacer
    - maligned
    - golint
    - ifshort
    - structcheck
    - nosnakecase
    - deadcode
    - varcheck

    # Linters that are disabled because of generics.
    - rowserrcheck
    - sqlclosecheck
    - wastedassign

    # Linters that are not used for this project.
    - cyclop
    - exhaustruct
    - goerr113
    - gomnd
    - gosec
    - nlreturn
    - paralleltest
    - testpackage
    - tparallel
    - wrapcheck
    - wsl
