project_name: retry

builds:
  - id: retry
    binary: retry

    goos:
      - darwin
      - windows
      - linux

    goarch:
      - amd64
      - 386

    ignore:
      - goos: darwin
        goarch: 386

    flags:
      - -trimpath

    ldflags:
      - -s -w
      - -buildid=
      - -X main.version={{.Version}}

    env:
      - CGO_ENABLED=0

    hooks:
      post: upx --best --ultra-brute "{{ .Path }}"

archives:
  - id: retry
    builds: [retry]
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}"

    format_overrides:
      - goos: windows
        format: zip

release:
  name_template: "{{.Tag}} Release"
  prerelease: auto

checksum:
  name_template: "checksums.txt"

changelog:
  skip: true
