project_name: retry

builds:
  - id: retry
    binary: retry

    goos:
      - darwin
      - windows
      - linux

    goarch:
      - amd64
      - 386

    ignore:
      - goos: darwin
        goarch: 386

    flags:
      - -trimpath

    ldflags:
      - -s -w
      - -buildid=
      - -X main.version={{.Version}}

    env:
      - CGO_ENABLED=0

    hooks:
      post: upx --best --ultra-brute "{{ .Path }}"

archives:
  - id: retry
    builds: [retry]
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}"

    format_overrides:
      - goos: windows
        format: zip

release:
  name_template: "{{.Tag}} Release"
  prerelease: auto

checksum:
  name_template: "checksums.txt"

changelog:
  skip: true

brews:
  - name: retry
    ids: [retry]

    tap:
      owner: joshdk
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"

    url_template: "https://github.com/joshdk/retry/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_msg_template: "feat: brew formula update for {{ .ProjectName }} {{ .Tag }}"
    commit_author:
      name: joshdk
      email: jdkomo@gmail.com

    folder: Formula

    caveats: "Run retry --help for usage"
    homepage: "https://github.com/joshdk/retry"
    description: "Rerun a command until it eventually succeeds, or doesn't"
    license: "MIT"

    test: |
      system "#{bin}/retry -version"
