project_name: retry

builds:
  - id: retry
    binary: retry

    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_386
      - windows_amd64

    flags:
      - -buildvcs=false
      - -trimpath

    ldflags:
      - -s -w
      - -buildid=
      - -X main.version={{.Version}}

    env:
      - CGO_ENABLED=0

archives:
  - id: retry
    builds: [retry]
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}"

    format_overrides:
      - goos: windows
        format: zip

release:
  name_template: "{{.Tag}} Release"
  prerelease: auto

checksum:
  name_template: "checksums.txt"

changelog:
  skip: true

brews:
  - name: retry

    tap:
      owner: joshdk
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"

    url_template: "https://github.com/joshdk/retry/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_msg_template: "feat: brew formula update for {{ .ProjectName }} {{ .Tag }}"
    commit_author:
      name: Josh Komoroske
      email: jdkomo@gmail.com

    folder: Formula

    caveats: "Run retry --help for usage"
    homepage: "https://github.com/joshdk/retry"
    description: "Rerun a command until it eventually succeeds, or doesn't"
    license: "MIT"

    test: |
      system "#{bin}/retry -version"
