#!/bin/sh
set -eu

platform="$(uname -s)"
if [ "$platform" = Linux ]; then
    prefix=goreleaser_Linux_x86_64
elif [ "$platform" = Darwin ]; then
    prefix=goreleaser_Darwin_x86_64
fi

cd "$(mktemp -d)" || exit 1
wget -q "https://github.com/goreleaser/goreleaser/releases/download/v0.164.0/${prefix}.tar.gz"
tar -xf "${prefix}.tar.gz"
mkdir -p "$(dirname "$1")"
install goreleaser "$1"
rm -rf "$PWD"
