#!/bin/sh
set -eu

platform="$(uname -s)"
if [ "$platform" = Darwin ]; then
    HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 exec brew install upx
fi
prefix=upx-3.94-amd64_linux

cd "$(mktemp -d)" || exit 1
wget -q "https://github.com/upx/upx/releases/download/v3.94/${prefix}.tar.xz"
tar -xf "${prefix}.tar.xz"
mkdir -p "$(dirname "$1")"
install "${prefix}/upx" "$1"
rm -rf "$PWD"
