name: Build
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build binary
        run: go build -o dist/retry -trimpath -ldflags="-s -w -X main.version=$(git describe --always)" .

      - name: Sanity check version
        run: ./dist/retry -version

  test:
    name: Test
    runs-on: ubuntu-22.04

    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: go test -v -race -cover ./...
