name: build
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Build binary
        run: go build -o dist/retry -ldflags="-s -w -X main.version=$(git describe --tags)" .

      - name: Sanity check version
        run: ./dist/retry -version

  golang-ci-lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Run GolangCI-Lint
        uses: docker://golangci/golangci-lint:v1.21.0-alpine
        with:
          entrypoint: /usr/bin/golangci-lint
          args: run -v
