name: Release
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Install UPX 3.94
        run: |
          wget -q https://github.com/upx/upx/releases/download/v3.94/upx-3.94-amd64_linux.tar.xz
          tar -xvf upx-3.94-amd64_linux.tar.xz
          mkdir -p /opt/hostedtoolcache/upx-3.94/bin
          install upx-3.94-amd64_linux/upx /opt/hostedtoolcache/upx-3.94/bin/upx
          rm -rf upx-3.94-amd64_linux*
          echo ::set-env name=PATH::/opt/hostedtoolcache/upx-3.94/bin:$PATH

      - name: Install GoReleaser 0.123.3
        run: |
          wget -q https://github.com/goreleaser/goreleaser/releases/download/v0.123.3/goreleaser_Linux_x86_64.tar.gz
          tar -xvf goreleaser_Linux_x86_64.tar.gz goreleaser
          mkdir -p /opt/hostedtoolcache/goreleaser-0.123.3/bin
          install goreleaser /opt/hostedtoolcache/goreleaser-0.123.3/bin/goreleaser
          rm -rf goreleaser*
          echo ::set-env name=PATH::/opt/hostedtoolcache/goreleaser-0.123.3/bin:$PATH

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goreleaser release
