name: Release
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup upx
        run: |-
          cd "$(mktemp -d)"
          wget -q https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
          tar -xf upx-3.96-amd64_linux.tar.xz
          sudo install upx-3.96-amd64_linux/upx /usr/bin/upx
          rm -rf "$PWD"

      - name: Build and publish release artifacts
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
