name: Release
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Release
    runs-on: ubuntu-22.04

    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and publish release artifacts
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
